name: Docker Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get project files
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t real-web-app .
